### PR TITLE
feat: initial setup

### PR DESCRIPTION
**Pull request by akhill10**
- Initial client library setup.
- Added request builder which uses axios.
- Added basic configuration options for tigris client.
- Added basic method to list the collections of database module
- Added developer productivity tools like eslint, prettier etc.

### CODE REVIEW

**Comment by garrensmith** [comment]
@akhill10 this is a good start. I would like you to make a few overall changes. In the long term it would be nice to merge this into the same repo as the other Tigris Typescript client and this is the client that does HTTP and the other will be the grpc client. Ideally the repo would then become a monorepo. So with that in mind. Could you change the `request-builder` to be `http` `driver`. Then have a `driver` interface. This interface will make all the network calls. You could maybe use openapi to generate some of this based of the proto/api we have.

**Review by garrensmith — CHANGES_REQUESTED** [review]
This is a good start. I've left another comment on where I want this to go.

**Comment by akhill10** [comment]
@garrensmith Thanks for the review. Sure, will make the changes accordingly. 
And can I use this package https://www.npmjs.com/package/openapi-typescript-codegen for generating those http calls from proto/api and use our client wrapper around it ?

**Comment by ovaistariq** [comment]
Based on @garrensmith suggestion I have renamed the repo to `tigris-client-http`

**Comment by akhill10** [comment]
@garrensmith Applied the changes. Please take a look.
Used [OpenAPI Typescript Codegen](https://www.npmjs.com/package/openapi-typescript-codegen) for generating those network calls. As it large number of files , didn't include this PR , so reviewing would be easy. Will be raising a separate PR for that, once this is merged. Included npm script to generate it.

**Review by garrensmith — APPROVED** [review]

**Comment by garrensmith** [comment]
@akhill10 this looks great. I've +1. Keep up the great work

**Comment by garrensmith** [comment]
@akhill10 could you sign the commit and then I can merge it in

**Comment by garrensmith** [comment]
@akhill10 could you squash the commits and that should sign the first commit

**Comment by akhill10** [comment]
@garrensmith I signed off all the commits. Can Squash merge it, please?

**Comment by ovaistariq** [comment]
@akhill10 amazing work. I have squash merged it.

**Pull request merged**
